name: Processar Feed XML

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

permissions:
  contents: write  # Permite fazer commit e push no repositório

jobs:
  process-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalar Dependências
        run: pip install requests

      - name: Garantir pasta json_parts existe
        run: |
          mkdir -p json_parts
          touch json_parts/.gitkeep

      - name: Baixar e Processar Feed XML
        run: |
          python script.py || { echo "Erro ao executar script.py"; exit 1; }

      - name: Gerar arquivo único merged.json
        run: |
          python merge_json.py || { echo "Erro ao executar merge_json.py"; exit 1; }

      - name: Verificar arquivos JSON antes do commit
        run: ls -lh json_parts/ || echo "A pasta está vazia ou não existe!"
      
      - name: Verificar merged.json antes do commit
        run: ls -lh merged.json || echo "merged.json não foi gerado!"

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit e Push dos Arquivos JSON
        run: |
          cd $GITHUB_WORKSPACE
          git add -f json_parts/
          git add -f merged.json
          git commit -m "Atualização automática dos arquivos JSON" || echo "Nada para commitar"
          git push || echo "Nenhuma alteração para enviar"

      - name: Verificar arquivos JSON depois do commit
        run: ls -lh json_parts/ || echo "A pasta está vazia ou não existe!"

      - name: Verificar merged.json depois do commit
        run: ls -lh merged.json || echo "merged.json não foi gerado!"
